### PR TITLE
converted to support node 6+ and not require babel

### PR DESCRIPTION
**Pull request by tlivings**
Resolves https://github.com/okgrow/merge-graphql-schemas/issues/31

### CODE REVIEW

**Comment by tlivings** [comment]
Any interest in this @RodMachado ?

**Comment by pauldowman** [comment]
@tlivings I'm having trouble understanding why we would want to do this. Can you explain? ES6 modules are the future. Actually they're the present.

**Comment by tlivings** [comment]
Most es6 is supported in Node6+ today. There is no need to be transpiling for any of the features you were using other than `import`. If you wish to use es6 module imports, then :+1: but at the very least it shouldn't require `babel-runtime` just to use this module.

**Comment by pauldowman** [comment]
Most are. But not `import`, which we want to use (it's been standard for 2 years). Node will always be behind so I don't think removing transpilation is a goal.

**Comment by tlivings** [comment]
This doesn't stop you from using import in projects that utilize this library. Import is buying you nothing other than syntax sugar here - but my main point was that consumers shouldn't be required to install babel when using this module (see linked issue).

**Comment by RodMachado** [comment]
Hey @tlivings! Sorry for not responding earlier!
 
I agree with @pauldowman in that we want to continue using `import` and babel for any future es6 features. I also find it really weird that you, as a user, are being required to install babel because of code that is not used by the package in a production environment, after all we do transpile it. 

So, here's what I propose. Instead of changing the `src` and `test` code to be compatible with current node version, how about if we changed the `publish` script to run from the `dist` folder, and by doing that, the published package would only contain the transpiled code. 

Currently we transpile the code with the `prepublish` script. We just need to change it so that it copies the `package.json` file to the `dist` folder. I'll change our Semaphore script to run `npm publish` from the `dist` folder.

I believe this would solve your issue. What do you think?

**Comment by tlivings** [comment]
@RodMachado afaik the problem is in the transpiled code for `merge_resolvers.js` as follows:

```
var _toConsumableArray2 = require('babel-runtime/helpers/toConsumableArray');
```

I don't think changing the publish behavior will help here.

I would recommend not transpiling all the way back to es2015. The node4 or node6 presets should be fine for your purposes since this is not an isomorphic module in the first place.

Thanks!

**Comment by tlivings** [comment]
I am closing the PR and leaving the issue #31 with the same comments to await resolution.

**Comment by tlivings** [comment]
@RodMachado Updated #31 with additional problem spots. Updating your preset should help quite a bit. Keep in mind that people may be consuming this module that are using node4+ and not transpiling code :)

**Pull request closed without merging**
