### PR TITLE
docs: update maintainers in readme

### PR DESCRIPTION
**Pull request by cfnelson**
**Changes Made:**
- Add cfnelson, RichardLitt & okgrow to maintainers.

### CODE REVIEW

**Comment by RichardLitt** [comment]
Looks good to me. Perhaps changing `Maintainer` to `# Maintainers`. Also, maybe a line about me being a support person, in general?

**Comment by cfnelson** [comment]
@RichardLitt Hehe, I was actually going to put your name in there! Wasn't sure if that would have been presumptuous of me. Will make the changes etc. Is there a specific line you had in mind for how to state your role?

I was also curious if you had seen or know of some decent default templates for PR's?

**Comment by RichardLitt** [comment]
I would just add "@RichardLitt (triage and basic support)". That should cover it pretty decently, make it clear I can't do the heavy lifting. 

Here's a list of [awesome pr templates](https://github.com/devspace/awesome-github-templates). That help?

**Comment by cfnelson** [comment]
@RichardLitt Thanks for the link, that is what I was talking about. I had looked at in the past and was trying to mash up a few different templates to create something that would work for us. Hadn't seen one yet that looked exactly right. 😂 

Have been using a very basic one like this -> 

🌟**Goal/Reason for this PR:** 🌟
This is an example of me describing the reason for my PR and what I am trying to achieve.

💃**Changes Made:** 💃 
- Added [rmwc](https://github.com/jamesmfriedman/rmwc) pkg. Using [material-components-web](https://github.com/material-components/material-components-web) for creating an app shell ui layout
- Created initial working/functional app shell layout with routing.

📓 **Notes:** 📓 
- Docs & advanced examples of styled-components usage with the [rmwc](https://jamesmfriedman.github.io/rmwc/styling#styled-components) pkg

 🏗**TODO:** 🏗
 
- [ ] Minor styling fixes.
- [ ] Task A
- [ ] Task B

**Comment by RichardLitt** [comment]
@cfnelson Yeah - it's a bit hard to get a good PR template due to tailoring. If your current one is changing, maybe don't fix it? If you have a suggestion for a new one, ping me - happy to take a look at it. :)

**Pull request merged**
