### PR TITLE
Update return type of `fileLoader` to be accepted by `mergeTypes`

### PR DESCRIPTION
**Pull request by koenpunt**
Followup of #170

### CODE REVIEW

**Comment by koenpunt** [comment]
> defeats the purpose of the typings to being with

True, but is probably unavoidable since the fileloader supports loading ts and ja files for which it uses `require`, which returns `any`..

**Comment by onehorsetown** [comment]
In Typescript, `require` does return `any`, but when an actual typescript or javascript file is loaded `typeof returnVal` is actually `string`:

https://github.com/okgrow/merge-graphql-schemas/blob/b0d0ae412e0f16cc5de5c2db10532d32d2b60ed9/src/file_loader.js#L60

I added a `console.log` statement and ran the tests.  All test cases that invoke `require` on line 60 return a `string`.

**Comment by koenpunt** [comment]
> I added a `console.log` statement and ran the tests. All test cases that invoke `require` on line 60 return a `string`.

If I run `console.log('returnVal =', typeof returnVal);`, I get `returnVal = object`.

**Comment by onehorsetown** [comment]
Indeed you are correct.  This returns an array of object:

https://github.com/okgrow/merge-graphql-schemas/blob/b0d0ae412e0f16cc5de5c2db10532d32d2b60ed9/test/file_loader.test.js#L50

which, if then passed off directly to `mergeTypes` is going to crash on line 158:

https://github.com/okgrow/merge-graphql-schemas/blob/b0d0ae412e0f16cc5de5c2db10532d32d2b60ed9/src/merge_types.js#L158

Seems like a no-win situation.

**Pull request merged**
