### PR TITLE
Fix #156

### LINKED ISSUE #156: Directives must appear exactly once on a field
Mayby bug.

Try to merge twice 
```
type User {
  id: ID! @unique
  fullname: String
}

type User {
  id: ID! @unique
  email: String
}
```

Got:
```
schema type User {
  id: ID! **@unique @unique**
  fullname: String
}
```
Error: The field `id` specifies a directive more than once. Directives must appear exactly once on a field.

### PR DESCRIPTION
**Pull request by Fi1osof**

### CODE REVIEW

**Comment by Fi1osof** [comment]
@cfnelson please, merge PR. It's critical for me. Thanks!

**Comment by Fi1osof** [comment]
@cfnelson thanks!

**Comment by cfnelson** [comment]
On mobile atm, will publish a npm release once I am back at a keyboard. Will be a few hours.

**Comment by cfnelson** [comment]
Should be able to use the master branch directly until then. Or if you wish to make a pr for a new release. I'll accept that and deploy the new version.

**Comment by Fi1osof** [comment]
@cfnelson  I do not quite understand, should I do something else?

**Comment by RichardLitt** [comment]
@Fi1osof I don't think so; I think that @cfnelson was just letting you know what you could use before he makes a new release. 

@cfnelson Have you published yet? :)

**Comment by cfnelson** [comment]
@Fi1osof Sorry about that, was asking if you'd bump the pkg version & CHANGELOG.md.  Sorry for not being clear.
I've been flat out & haven't had any time 😅 . It's published now and hopefully it fixes everything for you! 🙌 Bumped `npm` pkgs as well to fix reported security vulnerabilities. Release [v1.5.8]( https://github.com/okgrow/merge-graphql-schemas/releases/tag/v1.5.8)
cc @RichardLitt  the above ^

**Comment by Fi1osof** [comment]
@RichardLitt , @cfnelson ok, i got it. Thnaks. Will try next time.

**Pull request merged**
