### PR TITLE
Updated to graphql@14.0.2 and added it to the peer dependencies

### PR DESCRIPTION
**Pull request by polco**

### CODE REVIEW

**Comment by polco** [comment]
fixes https://github.com/okgrow/merge-graphql-schemas/issues/165

**Comment by RichardLitt** [comment]
Thanks, @polco!

**Comment by polco** [comment]
done @cfnelson

**Comment by cfnelson** [comment]
@polco Thanks for this, I'll test this out locally first before merging and will likely want to bundle this with the other open pr and hopefully publish a new pkg release later this week.

**Pull request merged**
