### PR TITLE
Added flag for mergeTypes to merge all types

### PR DESCRIPTION
**Pull request by squidfunk**
This PR adds the ability to merge custom types, as demanded [here](https://github.com/okgrow/merge-graphql-schemas/issues/113). Precisely, it adds an option to `mergeTypes`, so the behavior is entirely downward compatible. Tests are also included. Now we can do the following:

``` gql
# a.gql
type Custom {
  id: ID!
}

# b.gql
type Custom {
  name: String
  age: Int
}
```

Merge types with:

``` js
mergeTypes(types, { all: true })
```

Result:

``` gql
type Custom {
  id: ID!
  name: String
  age: Int
}
```

### CODE REVIEW

**Comment by squidfunk** [comment]
Thank you for the PR review. I will take a look and try to handle the two cases you discussed, but I may need some assistance/directions. I will keep you updated when I make progress.

**Comment by cfnelson** [comment]
@squidfunk No worries, will be happy to collaborate further to improve the PR and get it accepted. Having a working naive solution as a basis to work off would be a good starting point. We would want to have multiple tests to cover any other scenarios that we have yet to discuss as well.

**Comment by squidfunk** [comment]
Currently the problem with non-disjoint types (one field occurs in both type definitions) also applies to the mergeable type definitions (queries, mutations, subscriptions):

``` graphql
type Query {
  foo: Int
  bar: String
}
type Query {
  foo: String
  baz: Boolean
}
```

Results in:

``` graphql
schema {
  query: Query
}

type Query {
  foo: Int
  bar: String
  foo: String
  baz: Boolean
}
```

Therefore, in my opinion, it's not exclusively related to this PR. However, I will try to fix that too.

**Comment by squidfunk** [comment]
I covered the cases you specified in new test cases for custom types and for query types and seem to have fixed the stated issues. One issue remains: The **arguments** for fields (methods) of query types and custom types need to be checked prior to merging. However, this is also broken in the latest version and I would favor to do it in a separate PR (me or somebody else).

**Comment by squidfunk** [comment]
Fixed one more error for comment nodes

**Comment by cfnelson** [comment]
@squidfunk Thanks for the updates 🔥 . @RodMachado and myself will review and test these new updates hopefully sometime this week.

Did you have any opinions/thoughts on how to approach the argument fields issue? Attempt to resolve or throwing an error?

**Comment by squidfunk** [comment]
> Did you have any opinions/thoughts on how to approach the argument fields issue? Attempt to resolve or throwing an error?

I would do it exactly as with the field types - if the definitions match, just merge them, otherwise throw an error. We also have to check arity and input types, but I think this should be done in a separate PR.

**Comment by kohlikohl** [comment]
What is the status of this PR? 
Looks awesome and is exactly the addition to the library I am waiting for.
Anything I can do to help get this merged in?

**Comment by cfnelson** [comment]
@kohlikohl It's ready to go! Waiting for final review, though we shouldn't hold this up any longer.  We just need to update the README & CHANGELOG. After this is merged we can bump the pkg versions and publish to npm.
 
Any help with the above would be appreciated otherwise I will try to get it out in the next 24hrs.

**Comment by aoighost** [comment]
This is going to be awesome

**Comment by cfnelson** [comment]
@RodMachado Been waiting for your review. Planning to merge without it now.

**Pull request merged**
